language: objective-c

env:
  - TRAVIS_NODE_VERSION="6"

before_install:
  - npm install -g npm@latest
  - brew update
 
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - brew reinstall gradle watchman xctool
  - brew reinstall flow 0.23.0
 
branches:
  only:
    - master

script:
- |
  cd HappyOMeter/ios
  npm install
  flow check
  npm test



